"""empty message

Revision ID: 1a97094b14cc
Revises: 275db080cc4f
Create Date: 2023-07-05 14:08:03.752284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a97094b14cc'
down_revision = '275db080cc4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_map', 'added_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_map', sa.Column('added_by', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
