"""added added_by field

Revision ID: 275db080cc4f
Revises: 
Create Date: 2023-07-05 14:06:12.392904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275db080cc4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_map', sa.Column('added_by', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_map', 'added_by')
    # ### end Alembic commands ###
