"""empty message

Revision ID: 53dd5b27f2d4
Revises: 
Create Date: 2023-07-05 14:39:13.352638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53dd5b27f2d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_map', 'added_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_map', sa.Column('added_by', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
